/**
 * src/types/viva.ts
 * AI Code-Aware Viva System — TypeScript interfaces for Sarvam-powered viva sessions.
 *
 * Workflow:
 *   1. Student writes code in Monaco Editor
 *   2. Code submitted → Judge0 executes → results stored (runtime, memory, status)
 *   3. User starts viva → backend fetches submission + Judge0 results
 *   4. Sarvam receives: source code, topic, runtime, memory, execution status
 *   5. Sarvam identifies: algorithms, data structures, optimizations, complexity, weaknesses
 *   6. Personalized viva questions generated based on the analysis
 *   7. Multi-round Q&A with Sarvam-driven evaluation
 *
 * Backend Integration Notes:
 * - VivaSession stores the full conversation + Sarvam code analysis
 * - VivaQuestion.category maps to the analysis aspect that triggered it
 * - Scoring is derived from Sarvam's evaluation of each answer
 * - Passing threshold: 60/100 (configurable per topic)
 */

import { Submission } from './submission';
import { Topic } from './module';
import { User } from './user';

// ======================================================================
// Sarvam Code Analysis (input to viva question generation)
// ======================================================================

/**
 * The analysis output from Sarvam AI after examining a student's code.
 * This is the foundation for all viva questions.
 *
 * Sarvam Input: source_code, topic, runtime (ms), memory (KB), execution_status
 * Sarvam Output: algorithms, data structures, optimizations, complexity, weaknesses
 *
 * TODO: Implement Sarvam API call to generate this analysis
 * TODO: Map Sarvam response fields to this interface
 */
export interface VivaCodeAnalysis {
  algorithmsUsed: string[];
  dataStructuresUsed: string[];
  optimizations: string[];
  timeComplexity: string;
  spaceComplexity: string;
  weaknesses: string[];
  suggestions: string[];
}

// ======================================================================
// Viva Question
// ======================================================================

/**
 * A single viva question generated by Sarvam based on code analysis.
 *
 * Each question is tied to a specific aspect of the analysis:
 * - concept:  questions about theoretical understanding
 * - implementation: questions about code choices
 * - optimization: questions about performance trade-offs
 * - edge_cases: questions about error handling and boundary conditions
 *
 * The `sourceAnalysis` field links back to what in the code triggered this question
 * (e.g., "HashMap usage detected in line 12").
 */
export interface VivaQuestion {
  question: string;
  category: 'concept' | 'implementation' | 'optimization' | 'edge_cases';
  difficulty: 'easy' | 'medium' | 'hard';
  expectedKeyPoints: string[];
  sourceAnalysis?: string;
}

// ======================================================================
// Viva Message (single exchange in the conversation)
// ======================================================================

/**
 * A single message in the viva conversation.
 *
 * - role 'sarvam': questions asked by the AI
 * - role 'student': answers submitted by the student
 * - score: null for questions, 0-10 for student answers
 *
 * TODO: Store source analysis reference for each question
 */
export interface VivaMessage {
  role: 'sarvam' | 'student';
  content: string;
  score?: number | null;
  timestamp: string;
  category?: VivaQuestion['category'];
  difficulty?: VivaQuestion['difficulty'];
}

// ======================================================================
// Viva Session
// ======================================================================

export type VivaStatus = 'in_progress' | 'completed' | 'abandoned';

/**
 * Complete viva session with full context.
 *
 * Stores:
 * - User + submission + topic references
 * - Sarvam code analysis (used for question generation)
 * - Judge0 execution context (runtime, memory, status)
 * - Full conversation history
 * - Aggregate score and feedback
 */
export interface VivaSession {
  _id: string;
  user: string | User;
  submission: string | Submission;
  topic: string | Topic;
  codeAnalysis: VivaCodeAnalysis | null;
  executionContext: {
    runtime: number;
    memory: number;
    status: string;
  } | null;
  messages: VivaMessage[];
  totalScore: number;
  feedback: string;
  status: VivaStatus;
  isPassed: boolean;
  passingThreshold: number;
  createdAt: string;
  updatedAt: string;
}

// ======================================================================
// Viva API Contracts — Request/Response payloads
// ======================================================================

/**
 * Request: Start a new viva session for a given submission.
 *
 * Backend will:
 * 1. Fetch the submission + Judge0 results
 * 2. Call Sarvam with (code, topic, runtime, memory, status)
 * 3. Parse Sarvam's analysis into VivaCodeAnalysis
 * 4. Generate first viva question based on analysis
 * 5. Create and return VivaSession
 */
export interface VivaStartPayload {
  submissionId: string;
}

/**
 * Response: Viva session started with first question and code analysis.
 */
export interface VivaStartResponse {
  viva: VivaSession;
  firstQuestion: VivaQuestion;
  codeAnalysis: VivaCodeAnalysis;
}

/**
 * Request: Submit an answer to the current question.
 *
 * Backend will:
 * 1. Fetch the current viva session
 * 2. Call Sarvam to evaluate the answer against expected key points
 * 3. Score the answer (0-10)
 * 4. Generate next question or signal completion
 */
export interface VivaAnswerPayload {
  answer: string;
}

/**
 * Response: Evaluation result with next question (if continuing).
 */
export interface VivaAnswerResponse {
  viva: VivaSession;
  answerFeedback: string;
  answerScore: number;
  nextQuestion: VivaQuestion | null;
  isCompleted: boolean;
}

/**
 * Response: Viva session completed with final score and feedback.
 */
export interface VivaCompleteResponse {
  viva: VivaSession;
  summary: string;
  strengths: string[];
  improvements: string[];
  totalScore: number;
  isPassed: boolean;
}
